services:
  f5-tts-trt:
    image: soar97/triton-f5-tts:24.12
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - PYTHONIOENCODING=utf-8
      - MODEL=${MODEL:-F5TTS_v1_Base}
      - HF_ENDPOINT=${HF_ENDPOINT:-https://hf-mirror.com}
      - HF_HOME=/workspace/hf_cache
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./ckpts:/workspace/ckpts
      - ./tests:/workspace/tests
      - d:/CX-O/F5-TTS/hf_download:/workspace/hf_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      /bin/bash -c "
        pip install vocos &&
        rm -rf F5-TTS &&
        git clone https://github.com/SWivid/F5-TTS.git &&
        cd F5-TTS/src/f5_tts/runtime/triton_trtllm/ &&
        bash run.sh 0 4 ${MODEL:-F5TTS_v1_Base}
      "
