/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126416-g9997fd0606-20260905"
#endif /* AVUTIL_FFVERSION_H */
